### ISSUE TITLE
Bicho is not authenticating well at Github

### ISSUE THREAD

**Issue by albertinisg** [MetricsGrimoire/Bicho#147]
Doing several checks, we've realize that bicho requests to Github are not using authentication. After several iterations, Github returns the 403 error code. Doing a curl request with that user (an authenticated one with the same user) worked perfectly. A non authenticated one returns the same 403 error.

What we've tried so far, was the following:

<pre>
/usr/local/bin/bicho --db-user-out=**** --db-password-out= --db-database-out=****-d 1 -b github --backend-user=**** --backend-password=**** -u https://api.github.com/repos/owner/repo/issues
</pre>

After several tries against different repos, we started getting the message:

<pre>
The server could not fulfill the request Forbidden(403)
</pre>

But the thing is, using curl with the same user and password against the API to check the rate, we get:

<pre>
curl -i -u ****  https://api.github.com/rate_limit
...
"rate": {
    "limit": 5000,
    "remaining": 4183,
    "reset": 1427482531
  }
</pre>

And doing the request using curl and not Bicho, we get the wanted JSON:

<pre>
curl -i -u **** https://api.github.com/repos/owner/repo/issues
...
HTTP/1.1 200 OK
Server: GitHub.com
Date: Fri, 27 Mar 2015 18:35:15 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2569
Status: 200 OK
...
</pre>

So finally, doing the same request without login, we obtain the 403 error again:

<pre>
{
  "message": "API rate limit exceeded for 163.117.202.50. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
</pre>

 We should also discuss about start using the github3py for this purpose.

**Comment by sduenas** [comment]
The problem was that in `config` module, there is some code that checks whether the URL works or not. In the case of `github` backend, this request was done without authentication. In some cases, it leaded to exceed the rate limit.

What I decided was to ignore this check when `github` backend is selected. The right way of doing this is to use authentication for this request too, but as authentication methods are different on each platform, I thought that skip the check for `github` was the safest and easiest way to fix this bug.

This issue is closed by 08dab91
