### ISSUE TITLE
All GitHub issues do not have labels assigned

### ISSUE THREAD

**Issue by cachedout** [MetricsGrimoire/Bicho#154]
I'm running the HEAD of the master branch and I don't see any label information coming down:

```
MariaDB [bicho]> select count(*) from issues_ext_github where labels is null;
+----------+
| count(*) |
+----------+
|     9775 |
+----------+
1 row in set (0.00 sec)

MariaDB [bicho]> select count(*) from issues_ext_github where labels is not null;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

What additional information could I provide to help find a resolution to this issue?

**Comment by cachedout** [comment]
Additionally, I presume that what's supposed to be in there is a delimited list of labels. (Please correct me if I'm wrong!)

It would be *really* nice if labels were normalized in a way that we could query against them. This is a huge, huge feature for us.

**Comment by sduenas** [comment]
I'm gonna check it. It shouldn't be difficult to add.

**Comment by cachedout** [comment]
@sduenas Thank you! I'm excited to see what you find.

**Comment by iganchevup8** [comment]
Here are some more details about this issue.

In fact labels are filled into the 'type' column of the 'issues' table. More of it only one label is taken into account. I think the reason is this part of the code (lines 400 through 403 of the github backend).
```
        if bug['labels']:
            bug_type = bug['labels'][0]['name']   # FIXME
        else:
            bug_type = unicode('')
```
IMHO there should be a loop taking into account all the labels an issue might possibly have.
Something like 

```
        if bug['labels']:
            for i in range(0, len(bug['labels'])):
                bug_type.append (bug['labels'][i]['name']   # FIXME
        else:
            bug_type = unicode('')
```
Didn't try the code, but if you need, I can try to produce a patch.

Another thing is that (IMHO again) labels should go to the 'labels' column of the 'github_issues_ext' table, where  they are expected to be and not into the issues table.
